language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - cd scheduler

before_script: pip install docker-compose

script: docker-compose run scheduler-api su -c "python manage.py test"
